name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init ENV
      run: apt-fast install -y libnfnetlink-dev
    
    - name: Install libs
      run: |
        cd ${{github.workspace}}/libs/libnetfilter_queue-1.0.5
        ./configure && make && make install
        cd ${{github.workspace}}/libs/libmnl-1.0.4
        ./configure && make && make install
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
